"use client";

import { Sparkles, Info } from "lucide-react";
import { Badge } from "@zalem/ui/components/optics/badge";
import { Button } from "@zalem/ui/components/optics/button";
import {
  HoverCard,
  HoverCardTrigger,
  HoverCardContent,
} from "@zalem/ui/components/optics/hover-card";
import { cn } from "@zalem/ui/lib/utils";
import type { Id } from "@zalem/backend/convex/_generated/dataModel";

interface ThemeItem {
  theme: string;
  count: number;
  quote: string;
  reviewId: Id<"reviews">;
}

interface ConflictItem {
  topic: string;
  positiveCount: number;
  negativeCount: number;
  summary: string;
}

interface ReviewSummaryData {
  _id: string;
  productId: Id<"products">;
  reviewCount: number;
  averageRating: number;
  positives: ThemeItem[];
  negatives: ThemeItem[];
  conflicts: ConflictItem[];
  bestFor: string[];
  generatedAt: number;
  modelUsed: string;
  validationPassed: boolean;
}

interface ReviewSummaryProps {
  summary: ReviewSummaryData;
  onScrollToReview?: (reviewId: Id<"reviews">) => void;
}

export function ReviewSummary({ summary, onScrollToReview }: ReviewSummaryProps) {
  return (
    <div className="animate-in fade-in slide-in-from-bottom-1 duration-300 space-y-4">
      {/* header */}
      <div className="flex items-center gap-2">
        <Sparkles className="text-primary size-4" />
        <h4 className="text-sm font-semibold">What {summary.reviewCount} buyers say</h4>
      </div>

      {/* positives + negatives: 2 columns with vertical divider */}
      {(summary.positives.length > 0 || summary.negatives.length > 0) && (
        <div className="grid gap-5 sm:grid-cols-[1fr_auto_1fr]">
          {/* positives */}
          <div className="space-y-2.5">
            <p className="text-muted-foreground text-xs font-semibold uppercase tracking-wider">
              Buyers like
            </p>
            {summary.positives.map((theme) => (
              <ThemeRow
                key={theme.theme}
                theme={theme}
                dotColor="bg-emerald-500"
                onScrollToReview={onScrollToReview}
              />
            ))}
          </div>

          {/* vertical divider */}
          <div className="border-border hidden border-l border-dashed sm:block" />

          {/* negatives */}
          <div className="space-y-2.5">
            <p className="text-muted-foreground text-xs font-semibold uppercase tracking-wider">
              Common complaints
            </p>
            {summary.negatives.map((theme) => (
              <ThemeRow
                key={theme.theme}
                theme={theme}
                dotColor="bg-amber-500"
                onScrollToReview={onScrollToReview}
              />
            ))}
          </div>
        </div>
      )}

      {/* conflicts */}
      {summary.conflicts.length > 0 && (
        <div className="space-y-3">
          {summary.conflicts.map((conflict) => (
            <ConflictBar key={conflict.topic} conflict={conflict} />
          ))}
        </div>
      )}

      {/* bestFor + footer */}
      <div className="flex items-center justify-between gap-4">
        {summary.bestFor.length > 0 && (
          <div className="flex flex-wrap items-center gap-1.5">
            <span className="text-muted-foreground text-xs">Best for</span>
            {summary.bestFor.map((useCase) => (
              <Badge key={useCase} variant="outline" className="text-xs">
                {useCase}
              </Badge>
            ))}
          </div>
        )}

        <HoverCard>
          <HoverCardTrigger>
            <button className="text-muted-foreground flex shrink-0 cursor-default items-center gap-1 text-xs">
              <Info className="size-3" />
              <span>AI-generated</span>
              {!summary.validationPassed && <span className="text-amber-500">· unverified</span>}
            </button>
          </HoverCardTrigger>
          <HoverCardContent className="w-72 text-sm">
            <div className="space-y-2">
              <p className="font-medium">About this summary</p>
              <p className="text-muted-foreground text-xs leading-relaxed">
                This summary was generated by AI from {summary.reviewCount} customer reviews. Themes
                and counts are extracted automatically and may not perfectly reflect every review.
                Click any quote to see the original review it came from.
              </p>
              <p className="text-muted-foreground text-xs leading-relaxed">
                AI can sometimes misinterpret sentiment or miss context. Always read individual
                reviews for the full picture.
              </p>
            </div>
          </HoverCardContent>
        </HoverCard>
      </div>
    </div>
  );
}

// -- theme row --

function ThemeRow({
  theme,
  dotColor,
  onScrollToReview,
}: {
  theme: ThemeItem;
  dotColor: string;
  onScrollToReview?: (reviewId: Id<"reviews">) => void;
}) {
  return (
    <div>
      <div className="flex items-center gap-2">
        <span className={cn("size-1.5 shrink-0 rounded-full", dotColor)} />
        <span className="text-sm font-medium">{theme.theme}</span>
        <span className="text-muted-foreground text-xs">·</span>
        <span className="text-muted-foreground text-xs tabular-nums">
          {theme.count} {theme.count === 1 ? "review" : "reviews"}
        </span>
      </div>
      {theme.quote && (
        <div className="pl-[14px]">
          <Button
            variant="link"
            size="xs"
            className="text-muted-foreground h-auto p-0 text-xs italic leading-relaxed"
            onClick={() => onScrollToReview?.(theme.reviewId)}
          >
            &ldquo;
            {theme.quote.length > 80 ? `${theme.quote.slice(0, 80)}…` : theme.quote}
            &rdquo;
          </Button>
        </div>
      )}
    </div>
  );
}

// -- conflict bar --

function ConflictBar({ conflict }: { conflict: ConflictItem }) {
  const total = conflict.positiveCount + conflict.negativeCount;
  const positivePct = total > 0 ? (conflict.positiveCount / total) * 100 : 50;

  return (
    <div className="space-y-1.5">
      <div className="flex items-center justify-between">
        <span className="text-muted-foreground text-xs tabular-nums">
          {conflict.positiveCount} agree
        </span>
        <span className="text-sm font-medium">{conflict.topic}</span>
        <span className="text-muted-foreground text-xs tabular-nums">
          {conflict.negativeCount} disagree
        </span>
      </div>
      <div className="flex h-3 gap-0.5 overflow-hidden rounded-full">
        <div
          className="rounded-l-full bg-emerald-500 transition-all duration-700 ease-out"
          style={{ width: `${positivePct}%` }}
        />
        <div className="flex-1 rounded-r-full bg-amber-500" />
      </div>
      <p className="text-muted-foreground text-center text-xs leading-relaxed">
        {conflict.summary}
      </p>
    </div>
  );
}
